### ISSUE TITLE
No module named six (Burp extension)

### ISSUE THREAD

**Issue by DeliciousBounty** [nccgroup/blackboxprotobuf#42]
During the installation of the extender.py for the burp extension I encounter an error.
`Traceback (most recent call last):
  File "/Users/nathans/Documents/Tools/blackboxprotobuf/burp/blackboxprotobuf/burp/extender.py", line 41, in <module>
    import blackboxprotobuf
  File "/Users/nathans/Documents/Tools/blackboxprotobuf/burp/blackboxprotobuf/__init__.py", line 57, in <module>
    fix_protobuf()
  File "/Users/nathans/Documents/Tools/blackboxprotobuf/burp/blackboxprotobuf/__init__.py", line 43, in fix_protobuf
    import six
ImportError: No module named six`

I just solve by adding `import six` to
 the editor.py file

**Comment by rwinkelmaier-ncc** [comment]
Hi! Thanks for reporting this issue.

It looks like there is a missing import in `editor.py`, so I'll try to push a fix for that quickly. Though off the top of my head, it doesn't look the error you posted if from `editor.py`. Is it possible you hadn't run `git submodule update --init` when the error occured?

**Comment by rwinkelmaier-ncc** [comment]
Added the import in https://github.com/nccgroup/blackboxprotobuf/commit/d3c80f213e8990bfbe03c2c03e265f6ae4f9a142 and did not see missing six imports elsewhere.
